Controllers/SpecializationController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using HospitalClient.Models;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;
using static HospitalClient.Controllers.HomeController;

namespace HospitalClient.Controllers
{
    public class SpecializationController : Controller
    {
        public async Task<IActionResult> SpecializationDetails()

        {
            List<Specialization> Specializationdetails = new List<Specialization>();


            using (var client = new HttpClient())
            {

                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage Res = await client.GetAsync("https://localhost:7094/api/Specialization/Specialization");

                if (Res.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;

                    Specializationdetails = JsonConvert.DeserializeObject<List<Specialization>>(Response);

                }
                return View(Specializationdetails);
            }
        }
        public async Task<IActionResult> Specialities()

        {
            List<Specialization> Specializationdetails = new List<Specialization>();


            using (var client = new HttpClient())
            {

                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage Res = await client.GetAsync("https://localhost:7094/api/Specialization/Specialization");

                if (Res.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;

                    Specializationdetails = JsonConvert.DeserializeObject<List<Specialization>>(Response);

                }
                return View(Specializationdetails);
            }
        }
        [NoDirectAccess]
        public IActionResult AddSpecialization()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddSpecialization(Specialization specialization)
        {
            Specialization splobj = new Specialization();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(specialization), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:7094/api/Specialization", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    splobj = JsonConvert.DeserializeObject<Specialization>(apiResponse);
                }
            }
            return RedirectToAction("SpecializationDetails");
        }
        [NoDirectAccess]
        [HttpGet]
        public async Task<IActionResult> EditSpecialization(int SpecializationId)
        {
            TempData["SpecializationId"] = SpecializationId;
            Specialization splobj = new Specialization();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7094/api/Specialization/SpecializationId?SpecializationId=" + SpecializationId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    splobj = JsonConvert.DeserializeObject<Specialization>(apiResponse);
                }
            }
    
            return View(splobj);
        }

        [HttpPost]
        public async Task<IActionResult> EditSpecialization(Specialization specialization)
        {
            Specialization obj = new Specialization();
            using (var httpClient = new HttpClient())
            {
                int specializationId = specialization.SpecializationId;
                StringContent content = new StringContent(JsonConvert.SerializeObject(specialization), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("https://localhost:7094/api/Specialization/" + specializationId, content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    obj = JsonConvert.DeserializeObject<Specialization>(apiResponse);
                }
            }
            return RedirectToAction("SpecializationDetails");
        }
        [NoDirectAccess]
        [HttpGet]
        public async Task<IActionResult> DeleteSpecialization(int SpecializationId)
        {
            Specialization splobj = new Specialization();
            TempData["SpecializationId"] = SpecializationId;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7094/api/Specialization/SpecializationId?SpecializationId=" + SpecializationId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    splobj = JsonConvert.DeserializeObject<Specialization>(apiResponse);
                }
            }
            return View(splobj);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSpecialization(Specialization specialization)
        {
            int specializationId = Convert.ToInt32(TempData["SpecializationId"]);
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:7094/api/Specialization/" + specializationId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("SpecializationDetails");
        }
    }
}

Views/Admin/AppointmentDetails.cshtml
@model IEnumerable<HospitalClient.Models.AppointmentBooking>

@{
        Layout="~/Views/Shared/AdminLayout.cshtml";

    ViewData["Title"] = "AppointmentDetails";
}

<h1>Appointment Details</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppointmentTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorId)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.DoctorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PatientId)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.PatientName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AppointmentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppointmentDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppointmentTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorId)       
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor.DoctorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PatientId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patient.PatientName)
            </td>
           
        </tr>
}
    </tbody>
</table>

Views/Admin/DeleteDoctor.cshtml
@model HospitalClient.Models.DoctorRegistration

@{
        Layout="~/Views/Shared/AdminLayout.cshtml";

    ViewData["Title"] = "DeleteDoctor";
}

<h1>DeleteDoctor</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DoctorRegistration</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qualification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpecializationId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpecializationId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialization.SpecializationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialization.SpecializationName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10" hidden>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>
        <dd class = "col-sm-10" hidden>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
    </dl>
    
    <form asp-action="DeleteDoctor">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Admin/DoctorDetails.cshtml
@model IEnumerable<HospitalClient.Models.DoctorRegistration>

@{
        Layout="~/Views/Shared/AdminLayout.cshtml";

    ViewData["Title"] = "DoctorDetails";
}

<h1>DoctorDetails</h1>

<p>
    <button type="button"><a  asp-controller="Admin" asp-action="DoctorRegister">Add Doctor</a></button>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DoctorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qualification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpecializationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpecializationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.ConfirmPassword)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qualification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SpecializationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialization.SpecializationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.ConfirmPassword)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
            <a asp-action="EditDoctor" asp-route-DoctorId="@item.DoctorId" class="btn btn-sm btn-primary rounded-0"><i class="fa fa-pencil"></i> Edit </a>
            <a asp-action="DeleteDoctor" asp-route-DoctorId="@item.DoctorId" class="btn btn-sm btn-primary rounded-0"><i class="fa fa-pencil"></i> Delete </a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Admin/DoctorRegister.cshtml
@model HospitalClient.Models.DoctorRegistration

@{
        Layout=null;

    ViewData["Title"] = "DoctorRegister";
}


    <style>
    * {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body {
  background-size: cover;
  font-family: sans-serif;
}
.login-wrapper {
  height: 100vh;
  width: 100vw;
  display: flex;
  justify-content: center;
  align-items: center;
}
.form {
  position: relative;
  width: 200%;
  max-width: 380px;
  padding: 80px 40px 40px;
  background: rgba(0, 0, 0, 0.7);
  border-radius: 10px;
  color: #fff;
  box-shadow: 0 15px 25px rgba(0, 0, 0, 0.5);
}
.form::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 50%;
  height: 100%;
  background: rgba(255, 255, 255, 0.08);
  transform: skewX(-26deg);
  transform-origin: bottom left;
  border-radius: 10px;
  pointer-events: none;
}
.form img {
  position: absolute;
  top: -50px;
  left: calc(50% - 50px);
  width: 100px;
  background: rgba(255, 255, 255, 0.8);
  border-radius: 50%;
}
.form h2 {
  text-align: center;
  letter-spacing: 1px;
  margin-bottom: 2rem;
  color: white;
}
.form .input-group {
  position: relative;
}
.form .input-group input {
  width: 100%;
  padding: 10px 0;
  font-size: 1rem;
  letter-spacing: 1px;
  margin-bottom: 30px;
  border: none;
  border-bottom: 1px solid #fff;
  outline: none;
  background-color: transparent;
  color: inherit;
}
.form .input-group label {
  position: absolute;
  top: 0;
  left: 0;
  padding: 10px 0;
  font-size: 1rem;
  pointer-events: none;
  transition: 0.3s ease-out;
}
.form .input-group input:focus + label,
.form .input-group input:valid + label {
  transform: translateY(-18px);
  color: white;
  font-size: 0.8rem;
}
.submit-btn {
  display: block;
  margin-left: auto;
  border: none;
  outline: none;
  background: #ff652f;
  font-size: 1rem;
  text-transform: uppercase;
  letter-spacing: 1px;
  padding: 10px 20px;
  border-radius: 5px;
  cursor: pointer;
}
.forgot-pw {
  color: inherit;
}

#forgot-pw {
  position: absolute;
  display: flex;
  justify-content: center;
  align-items: center;
  top: 0;
  left: 0;
  right: 0;
  height: 0;
  z-index: 1;
  background: #fff;
  opacity: 0;
  transition: 0.6s;
}
#forgot-pw:target {
  height: 100%;
  opacity: 1;
}
.close {
  position: absolute;
  right: 1.5rem;
  top: 0.5rem;
  font-size: 2rem;
  font-weight: 900;
  text-decoration: none;
  color: inherit;
}
body {
  background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWtsnzhHlGWhQC8mDduhhwco0CL9EOTa6dLg&usqp=CAU');
}
</style>



<head>
  <link rel="stylesheet" href="style.css" />
</head>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="style.css" />
    <title>Doctor Registration</title>
  </head>
  <body>
    <div class="login-wrapper">
      <form asp-action="DoctorRegister" class="form">
        <h2>Doctor Registration</h2>
        <div class="input-group">
          <input type="text" name="DoctorId" id="DoctorId" required />
          <label for="DoctorId">Doctor Email</label>
        </div>
        <div class="input-group">
          <input type="text" name="DoctorName" id="DoctorName" required />
          <label for="DoctorName">Doctor Name</label>
        </div>
        <div class="input-group">
          <input type="text" name="Qualification" id="Qualification" required />
          <label for="Qualification">Qualification</label>
        </div>
         <label>Specialization Name</label>
        <div class="input-group">


<select asp-for="SpecializationId"  asp-items="ViewBag.ClientsList1" >
                <option style="color:black">Select Specialization </option> </select> 
               @* <span asp-validation-for="SpecializationId" class="text-danger"></span>*@

            </div>
        <div class="input-group">
          <input type="text" name="Position" id="Position" required />
          <label for="Position">Position</label>
        </div>
        
        <div class="input-group">
          <input type="text" name="PhoneNumber" id="PhoneNumber" required />
          <label for="PhoneNumber">PhoneNumber</label>
        </div>
        <div class="input-group">
          <input type="text" name="Address" id="Address" required />
          <label for="Address">Address</label>
        </div>

        <div class="input-group">
          <input
            type="password"
            name="Password"
            id="Password"
            required
          />
          <label for="Password">Password</label>
        </div>
        <div class="input-group">
          <input
            type="password"
            name="ConfirmPassword"
            id="ConfirmPassword"
            required
          />
          <label for="ConfirmPassword">ConfirmPassword</label>
        </div>
        <div class="input-group">
          <input type="text" name="StartTime" id="StartTime" required />
          <label for="StartTime">StartTime</label>
        </div>
         <div class="input-group">
          <input type="text" name="EndTime" id="EndTime" required />
          <label for="EndTime">EndTime</label>
        </div>
        <input type="submit" value="Register" class="submit-btn" />
      </form>
    </div>
  </body>
</html>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
}

Views/Admin/EditDoctor.cshtml
@model HospitalClient.Models.DoctorRegistration

@{
        Layout="~/Views/Shared/AdminLayout.cshtml";

    ViewData["Title"] = "EditDoctor";
}

<h1>EditDoctor</h1>

<h4>DoctorRegistration</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditDoctor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <input asp-for="DoctorId" class="form-control" />
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorName" class="control-label"></label>
                <input asp-for="DoctorName" class="form-control" />
                <span asp-validation-for="DoctorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qualification" class="control-label"></label>
                <input asp-for="Qualification" class="form-control" />
                <span asp-validation-for="Qualification" class="text-danger"></span>
            </div>
           @* <div class="form-group">
                <label asp-for="SpecializationId" class="control-label"></label>
                <input asp-for="SpecializationId" class="form-control" />
                <span asp-validation-for="SpecializationId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label>Specialization Name</label>
                <select class ="form-control" asp-for="SpecializationId"  asp-items="ViewBag.ClientsList1" >
                <option style="color:black">Select Specialization </option> </select>
                <span asp-validation-for="SpecializationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Admin/Index.cshtml
@{
    Layout="~/Views/Shared/AdminLayout.cshtml";
    ViewData["Title"] = "Index";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

<style>.toast-top-center { 
    top: 12px;   
    
    left: 50%;   
     margin:0 0 0 -150px;
}</style>
   @if (TempData["Success"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                toastr.success('@TempData["Success"]', '', { positionClass: 'toast-top-center' });
            });
        </script>
    }
    
   @if (TempData["Message"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                toastr.Error('@TempData["Message"]', '', { positionClass: 'toast-top-center' });
            });
        </script>
    }
       
   @if (TempData["Mes"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                toastr.Error('@TempData["Mes"]', '', { positionClass: 'toast-top-center' });
            });
        </script>
    }


<body>

    <button type="button"><a  asp-controller="Admin" asp-action="DoctorRegister">Doctor Registration</a></button>

     <button type="button"><a  asp-controller="Admin" asp-action="DoctorDetails">Doctor Details</a></button>
      <button type="button"><a  asp-controller="Admin" asp-action="PatientDetails">Patient Details</a></button>
            <button type="button"><a  asp-controller="Admin" asp-action="AppointmentDetails">Appointment Details</a></button>
                  <button type="button"><a  asp-controller="Specialization" asp-action="SpecializationDetails">Specializations </a></button>

</body>

Views/Admin/Login.cshtml
@model HospitalClient.Models.Admin

@{
    Layout = null;
    ViewData["Title"] = "Login";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

<style>.toast-top-center { 
    top: 12px;   
    
    left: 50%;   
     margin:0 0 0 -150px;
}
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body {
  background-size: cover;
  font-family: sans-serif;
}
.login-wrapper {
  height: 100vh;
  width: 100vw;
  display: flex;
  justify-content: center;
  align-items: center;
}
.form {
  position: relative;
  width: 100%;
  max-width: 380px;
  padding: 80px 40px 40px;
  background: rgba(0, 0, 0, 0.7);
  border-radius: 10px;
  color: #fff;
  box-shadow: 0 15px 25px rgba(0, 0, 0, 0.5);
}
.form::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 50%;
  height: 100%;
  background: rgba(255, 255, 255, 0.08);
  transform: skewX(-26deg);
  transform-origin: bottom left;
  border-radius: 10px;
  pointer-events: none;
}
.form img {
  position: absolute;
  top: -50px;
  left: calc(50% - 50px);
  width: 100px;
  background: rgba(255, 255, 255, 0.8);
  border-radius: 50%;
}
.form h2 {
  text-align: center;
  letter-spacing: 1px;
  margin-bottom: 2rem;
  color: white;
}
.form .input-group {
  position: relative;
}
.form .input-group input {
  width: 100%;
  padding: 10px 0;
  font-size: 1rem;
  letter-spacing: 1px;
  margin-bottom: 30px;
  border: none;
  border-bottom: 1px solid #fff;
  outline: none;
  background-color: transparent;
  color: inherit;
}
.form .input-group label {
  position: absolute;
  top: 0;
  left: 0;
  padding: 10px 0;
  font-size: 1rem;
  pointer-events: none;
  transition: 0.3s ease-out;
}
.form .input-group input:focus + label,
.form .input-group input:valid + label {
  transform: translateY(-18px);
  color: white;
  font-size: 0.8rem;
}
.submit-btn {
  display: block;
  margin-left: auto;
  border: none;
  outline: none;
  background: #ff652f;
  font-size: 1rem;
  text-transform: uppercase;
  letter-spacing: 1px;
  padding: 10px 20px;
  border-radius: 5px;
  cursor: pointer;
}
.forgot-pw {
  color: inherit;
}

#forgot-pw {
  position: absolute;
  display: flex;
  justify-content: center;
  align-items: center;
  top: 0;
  left: 0;
  right: 0;
  height: 0;
  z-index: 1;
  background: #fff;
  opacity: 0;
  transition: 0.6s;
}
#forgot-pw:target {
  height: 100%;
  opacity: 1;
}
.close {
  position: absolute;
  right: 1.5rem;
  top: 0.5rem;
  font-size: 2rem;
  font-weight: 900;
  text-decoration: none;
  color: inherit;
}
body {
  background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWtsnzhHlGWhQC8mDduhhwco0CL9EOTa6dLg&usqp=CAU');
}

</style>
   @if (TempData["Success"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                toastr.success('@TempData["Success"]', '', { positionClass: 'toast-top-center' });
            });
        </script>
    }
    
<head>
  <link rel="stylesheet" href="style.css" />
</head>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="style.css" />
    <title>Login</title>
  </head>
  <body>
    <div class="login-wrapper">
      <form asp-action="Login" class="form">
        <h2>Admin Login</h2>
        <div class="input-group">
          <input type="text" name="AdminId" id="AdminId" required />
          <label for="AdminId">Admin Email</label>
        </div>

        <div class="input-group">
          <input
            type="password"
            name="Password"
            id="Password"
            required
          />
          <label for="Password">Password</label>
        </div>
        <input type="submit" value="Login" class="submit-btn" />
      </form>
    </div>
  </body>
</html>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}